import type { LanguagesType } from "#imports";

export default {
	en: {
		preHeadingLink: { label: "Learn more", link: "#" },
		preHeading: "Data overview",
		heading: "Team <span>Directory</span>",
		description: "A snapshot of your team members and their current status.",
		emptyMessage: "No data to display yet.",
		columns: [
			{ id: 1, label: "Member", type: "text" },
			{ id: 2, label: "Role", type: "text" },
			{ id: 3, label: "Bio", type: "textarea" },
			{ id: 4, label: "Photo", type: "image" },
			{ id: 5, label: "Active", type: "toggle" },
			{ id: 6, label: "Skills", type: "tags" },
		],
		items: [
			{
				1: "Alice Johnson",
				2: "Engineering Lead",
				3: "Leads the platform team and owns the architecture roadmap.",
				4: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["Leadership", "Architecture"],
			},
			{
				1: "Bob Smith",
				2: "Product Designer",
				3: "Designs end-to-end experiences across the product suite.",
				4: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["UI", "Prototyping"],
			},
			{
				1: "Carol Lee",
				2: "Marketing Manager",
				3: "Runs campaigns and brand storytelling across channels.",
				4: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
				5: false,
				6: ["Brand", "SEO"],
			},
		],
	},
	ar: {
		preHeadingLink: { label: "اعرف المزيد", link: "#" },
		preHeading: "نظرة عامة على البيانات",
		heading: "دليل <span>الفريق</span>",
		description: "نظرة عامة على أعضاء فريقك وحالتهم الحالية.",
		emptyMessage: "لا توجد بيانات لعرضها بعد.",
		columns: [
			{ id: 1, label: "العضو", type: "text" },
			{ id: 2, label: "الدور", type: "text" },
			{ id: 3, label: "نبذة", type: "textarea" },
			{ id: 4, label: "الصورة", type: "image" },
			{ id: 5, label: "نشط", type: "toggle" },
			{ id: 6, label: "المهارات", type: "tags" },
		],
		items: [
			{
				1: "أليس جونسون",
				2: "مسؤولة الهندسة",
				3: "تقود فريق المنصة وتشرف على خارطة طريق البنية التقنية.",
				4: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["قيادة", "بنية تقنية"],
			},
			{
				1: "بوب سميث",
				2: "مصمم منتجات",
				3: "يصمم تجارب متكاملة عبر مجموعة المنتجات.",
				4: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["واجهات", "نماذج أولية"],
			},
			{
				1: "كارول لي",
				2: "مديرة التسويق",
				3: "تدير الحملات وسرد قصة العلامة التجارية عبر القنوات.",
				4: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
				5: false,
				6: ["علامة تجارية", "تحسين محركات البحث"],
			},
		],
	},
	fr: {
		preHeadingLink: { label: "En savoir plus", link: "#" },
		preHeading: "Aperçu des données",
		heading: "Annuaire de l'<span>équipe</span>",
		description:
			"Un aperçu des membres de votre équipe et de leur statut actuel.",
		emptyMessage: "Aucune donnée à afficher pour le moment.",
		columns: [
			{ id: 1, label: "Membre", type: "text" },
			{ id: 2, label: "Rôle", type: "text" },
			{ id: 3, label: "Bio", type: "textarea" },
			{ id: 4, label: "Photo", type: "image" },
			{ id: 5, label: "Actif", type: "toggle" },
			{ id: 6, label: "Compétences", type: "tags" },
		],
		items: [
			{
				1: "Alice Johnson",
				2: "Cheffe d'ingénierie",
				3: "Dirige l'équipe plateforme et pilote la feuille de route technique.",
				4: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["Leadership", "Architecture"],
			},
			{
				1: "Bob Smith",
				2: "Designer produit",
				3: "Conçoit des expériences complètes à travers la suite produit.",
				4: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["UI", "Prototypage"],
			},
			{
				1: "Carol Lee",
				2: "Responsable marketing",
				3: "Pilote les campagnes et le storytelling de la marque.",
				4: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
				5: false,
				6: ["Marque", "SEO"],
			},
		],
	},
	es: {
		preHeadingLink: { label: "Más información", link: "#" },
		preHeading: "Resumen de datos",
		heading: "Directorio del <span>equipo</span>",
		description: "Un vistazo a los miembros de tu equipo y su estado actual.",
		emptyMessage: "No hay datos para mostrar aún.",
		columns: [
			{ id: 1, label: "Miembro", type: "text" },
			{ id: 2, label: "Rol", type: "text" },
			{ id: 3, label: "Bio", type: "textarea" },
			{ id: 4, label: "Foto", type: "image" },
			{ id: 5, label: "Activo", type: "toggle" },
			{ id: 6, label: "Habilidades", type: "tags" },
		],
		items: [
			{
				1: "Alice Johnson",
				2: "Líder de ingeniería",
				3: "Lidera el equipo de plataforma y posee la hoja de ruta de arquitectura.",
				4: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["Liderazgo", "Arquitectura"],
			},
			{
				1: "Bob Smith",
				2: "Diseñador de producto",
				3: "Diseña experiencias de extremo a extremo en toda la suite.",
				4: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
				5: true,
				6: ["UI", "Prototipado"],
			},
			{
				1: "Carol Lee",
				2: "Gerente de marketing",
				3: "Gestiona campañas y la narrativa de la marca en todos los canales.",
				4: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
				5: false,
				6: ["Marca", "SEO"],
			},
		],
	},
} satisfies Record<LanguagesType, DataTableBlock>;
